version: '3.7'
services:
  node-app:
    build: ./artifacts/gate-simulator
    image: latest
    container_name: node
    ports:
      - '9999:9999'
  postgres:
    image: latest
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/pgdata
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=app